config/routes.rb
Mealplanner::Application.routes.draw do
  post '/shopping/list', to: 'shopping#list', as: 'shopping_list'
  get '/shopping/setup', to: 'shopping#setup', as: 'shopping_setup'
  get '/shopping', to: 'shopping#setup', as: 'shopping'

  resources :recipes
  resources :meals
  resources :days
  resources :day_meal_relationships

  root :to => "days#index"

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :day_meal_relationships
  has_many :meals, :through => :day_meal_relationships

  accepts_nested_attributes_for :day_meal_relationships

  def total(item)
    return self.meals.map { |m| m.total(item) == nil ? 0 : m.total(item) }.inject(:+)
  end
end

app/models/day_meal_relationship.rb
class DayMealRelationship < ActiveRecord::Base
  belongs_to :meal
  belongs_to :day
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  include ColorizeModule

  has_many :day_meal_relationships
  has_many :days, :through => :day_meal_relationships
  has_many :meal_recipe_relationships
  has_many :recipes, :through => :meal_recipe_relationships
  validates_inclusion_of :meal_type, :in => %w(Breakfast Lunch Dinner Snack)

  def total(item)
    total = recipes.map { |r| r[item] }.inject(:+)

    # If there is no decimal, then chop off the ".0" part
    return total.round if total == total.round
    return total.round(2) # Otherwise round to two decimal places
  end

  def colorized_calories
    return if self.total('calories').nil?

    return colorize(self.total('calories'), {
      :danger => 500,
      :warning => 250
    })
  end

  def colorized_carbs
    return if self.total('carbs').nil?

    return colorize(self.total('carbs'), {
      :danger => 40,
      :warning => 20
    })
  end

  def colorized_fats
    return if self.total('carbs').nil?

    return colorize(self.total('fats'), {
      :danger => 20,
      :warning => 10
    })
  end
  
  def colorized_protein
    return if self.total('protein').nil?

    return colorize(self.total('protein'), {
      :success => 20,
      :warning => 10
    })
  end
end

app/models/meal_recipe_relationship.rb
class MealRecipeRelationship < ActiveRecord::Base
  belongs_to :meal
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include ColorizeModule

  validates :title, presence: true

  has_many :ingredients
  has_many :meal_recipe_relationships
  has_many :meals, :through => :meal_recipe_relationships

  accepts_nested_attributes_for :ingredients,
    allow_destroy: true,
    reject_if: lambda { |attributes| attributes['description'].blank? }

  has_attached_file :photo, :styles => { :medium => "300x300", :thumb => "100x100" }

  def batch_ingredients=(text)
    self.ingredients_attributes = text.split("\n").map { |t| { :description => t } }
  end

  def batch_ingredients
    return self.ingredients.map { |i| i.description }.join("\n")
  end

  def colorized_calories
    return if calories.nil?

    return colorize(calories, {
      :danger => 500,
      :warning => 250
    })
  end

  def colorized_carbs
    return if carbs.nil?

    return colorize(carbs, {
      :danger => 40,
      :warning => 20
    })
  end

  def colorized_fats
    return if carbs.nil?

    return colorize(fats, {
      :danger => 20,
      :warning => 10
    })
  end
  
  def colorized_protein
    return if protein.nil?

    return colorize(protein, {
      :success => 20,
      :warning => 10
    })
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/day_meal_relationships_controller.rb
class DayMealRelationshipsController < ApplicationController
  def create
    @relationship = DayMealRelationship.new(relationship_params)
    
    if @relationship.save
      redirect_to meals_path
    else
      render text: 'Error'
    end
  end

  private
    def relationship_params
      params.require(:day_meal_relationship).permit(:id, :meal_id, :day_id, :meal_ids)
    end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all
    @meals = Meal.all(:order => "FIELD(meal_type, 'Breakfast', 'Lunch', 'Snack', 'Dinner')")
  end

  def update
    @day = Day.find(params[:id])

    meal_ids = params['day']['meal_ids']
    meal_ids = [] if meal_ids.nil?
    meal_ids = [meal_ids] if false == meal_ids.kind_of?(Array)

    @day.meals = Meal.find(meal_ids)

    if @day.update(day_params)
      redirect_to days_path
    else
      render text: "couldn't update"
    end
  end

  private
    def day_params
      params.require(:day).permit(:id, :title)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def update
    @meal = Meal.find(params[:id])
    @meal.recipe_ids = params["meal"]["recipe_ids"]

    if @meal.update(meal_params)
      redirect_to edit_meal_path(@meal)
    else
      render 'edit'
    end
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.recipe_ids = params["meal"]["recipe_ids"]

    if @meal.save
      redirect_to @meal
    else
      render 'new'
    end
  end

  private
    def meal_params
      params.require(:meal).permit(:id, :meal_type, :recipe_ids)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:batch_ingredients, :title, :calories, :carbs, :fats, :protein, :servings, :url, :notes, :photo, ingredients_attributes: [:id, :description])
    end
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  def setup
    @days = Day.all
  end

  def list
    @directions = params["shopping"]["directions"] == "1" ? true : false

    @recipe_ids = strip_prefixes(params["shopping"]["recipe_ids"])

    @days = Day.all
    #render 'list', layout: 'simple'
  end

  private
    def strip_prefixes hash
      if hash.is_a?(Hash)
        return Hash[hash.map { |k, v| [get_id(k), strip_prefixes(v)] }]
      else
        return hash.map { |h| h.to_i }
      end
    end

    def get_id str
      str.gsub('day_', '').gsub('meal_', '').to_i
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/day_meal_relationships_helper.rb
module DayMealRelationshipsHelper
end

app/helpers/days_helper.rb
module DaysHelper
  def recipe_list(meal)
    return meal.recipes.map { |r| link_to r.title, recipe_path(r.id) }.join(', ').html_safe
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/days/_mealmodal.html.erb
<div class='modal fade meal-modal' id='add-meal-modal-<%= day.id %>' role="dialog">
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'>&times;</button>
        <h4 class='modal-title'>Change Meals for <%= day.title %></h4>
      </div>

      <div class='modal-body'>

        <%= form_for day do |f| %>
          <%= f.hidden_field :day_id, :value => day.id %>

          <div class='list-group'>
            <% meals.each do |meal| %>
              <a role='presentation' href='#' class='list-group-item'>
                <%= check_box_tag("day[meal_ids][]", meal.id, day.meals.include?(meal)) %>

                <strong><%= meal.meal_type %></strong>


                <div class='nutrition'>
                  <% %w(calories carbs fats protein).each do |n| %>
                    <span class='label label-warning'><span><%= n %></span><%= meal.total(n) %></span>&nbsp;
                  <% end %>
                </div>

        
                <ul>
                  <% meal.recipes.each do |recipe| %>
                    <li><%= recipe.title %></li>
                  <% end %>
                </ul>
              </a>
            <% end %>
          </div>
        <% end %>
        
      </div>

      <div class='modal-footer'>
        <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
        <button type='button' class='btn btn-primary add-meals'>Save</button>
      </div>
    </div>
  </div>
</div>

<button class='btn' data-toggle='modal' data-target='#add-meal-modal-<%= day.id %>'>
Change
</button>

app/views/days/_mealpicker.html.erb
<div class='dropdown'>
  <button class='btn dropdown-toggle' type='button' data-toggle='dropdown'>
    Add Meal
  </button>

  <div class='dropdown-menu list-group' role='menu'>
    <% meals.each do |meal| %>
      <a role='presentation' href='#' class='list-group-item'>

        <strong><%= meal.meal_type %></strong>

        <ul>
          <% meal.recipes.each do |recipe| %>
            <li><%= recipe.title %></li>
          <% end %>
        </ul>
        
        <%= form_for :day_meal_relationship, :url => day_meal_relationships_path do |f| %>
          <%= f.hidden_field :day_id, :value => day.id %>
          <%= f.hidden_field :meal_id, :value => meal.id %>
        <% end %>
      </a>
    <% end %>
  </ul>
</div>

app/views/days/_progressbar.html.erb
<div class='progress'>
  <div class='progress-bar <%= 'progress-bar-danger' if value > max %>' role='progressbar' style='width:<%= value.to_f / max.to_f * 100.0 %>%'>
  </div>
</div>

app/views/days/index.html.erb
<h1>Days</h1>

<% @days.each do |day| %>
  <div class='row'>
    <div class='col-md-2'>
      <%= day.title %>
    </div>
  
    <div class='col-md-5'>
      <% day.meals.each do |meal| %>
        <div class='row'>
          <div class='col-md-12'>
            <strong><%= meal.meal_type %></strong> - 
            <%= recipe_list(meal) %>
          </div>
        </div>
      <% end %>

      <%= render partial: 'mealmodal', locals: { day: day, meals: @meals } %>
    </div>
      
      <div class='col-md-5'>
        <% if day.meals.length > 0 %>
          <strong>Calories</strong>
          <%= day.total('calories') %>/2800
          <%= render partial: 'progressbar', locals: { max: 2800, value: day.total('calories') } %>

          <strong>Carbohydrates</strong>
          <%= day.total('carbs') %>/498
          <%= render partial: 'progressbar', locals: { max: 498, value: day.total('carbs') } %>
          <strong>Fats</strong>
          <%= day.total('fats') %>/119
          <%= render partial: 'progressbar', locals: { max: 119, value: day.total('fats') } %>
          <strong>Protein</strong>
          <%= day.total('protein') %>/65
          <%= render partial: 'progressbar', locals: { max: 65, value: day.total('protein') } %>
        <% end %>
      </div>
  </div>

  <hr />
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Days', days_path %></li>
<li><%= link_to 'Meals', meals_path %></li>
<li><%= link_to 'Recipes', recipes_path %></li>
<li><%= link_to 'Shopping List', shopping_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mealplanner" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mealplanner" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class='container'>
        <main role="main" class='col-md-12'>
           <%= render 'layouts/messages' %>
           <%= yield %>
        </main>
    </div>
  </body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mealplanner" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mealplanner" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
    </header>
    <div class='container'>
        <main role="main" class='col-md-12'>
           <%= render 'layouts/messages' %>
           <%= yield %>
        </main>
    </div>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_for @meal, url: meals_path(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <h2>Error:</h2>
    <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= select(:meal, :meal_type, [
    'Breakfast',
    'Lunch',
    'Dinner',
    'Snack'
  ].collect { |t| [t, t] }) %>

  <h2>Recipes</h2>

  
  <%= text_field_tag 'recipe-search', '', placeholder: 'filter recipes' %>

  <div class='list-group recipes'>
    <% Recipe.all.each do |recipe| %>
      <a role='presentation' href='#' class='list-group-item'>
        <%= check_box_tag "meal[recipe_ids][]", recipe.id, @meal.recipes.include?(recipe) %>
        <strong class='title'><%= recipe.title %></strong>

        <% if recipe.photo.exists? %>
          <%= image_tag recipe.photo.url(:thumb) %>
        <% end %>
      </a>
    <% end %>
  </div>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/meals/_summary.html.erb
<%= link_to meal.meal_type, edit_meal_path(meal.id) %>

<%= render partial: 'totals', locals: { meal: meal } %>

<ul>
  <% meal.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe.id) %></li>
  <% end %>
</ul>

app/views/meals/_totals.html.erb
<table>
  <tr>
    <td><%= meal.totals[:calories] %> calories</td>
    <td><%= meal.totals[:carbs] %> carbs</td>
    <td><%= meal.totals[:fats] %> fats</td>
    <td><%= meal.totals[:protein] %> protein</td>
  </tr>
</table>

app/views/meals/create.html.erb
<h1>Meals#create</h1>
<p>Find me in app/views/meals/create.html.erb</p>

app/views/meals/edit.html.erb
<h1>Edit Meal</h1>

<%= render partial: 'totals', locals: { meal: @meal } %>

<%= render partial: 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Meals</h2>
<%= link_to 'Add new', new_meal_path %>

<table class='table table-striped'>
  <tr>
    <th></th>
    <th></th>
    <th>Calories</th>
    <th>Carbohydrates (g)</th>
    <th>Fats (g)</th>
    <th>Protein (g)</th>
    <th></th>
  </tr>

  <% @meals.each do |meal| %>
    <tr>
        <td><%= meal.meal_type %></td>
        <td>
          <ul>
            <% meal.recipes.each do |recipe| %>
              <li><%= recipe.title %></li>
            <% end %>
          </ul>
        </td>
        <td><%= meal.colorized_calories %></td>
        <td><%= meal.colorized_carbs %></td>
        <td><%= meal.colorized_fats %></td>
        <td><%= meal.colorized_protein %></td>

        <td>
          <%= form_for :day_meal_relationship, :url => day_meal_relationships_path do |f| %>
            <div class='input-group'>
              <%= f.hidden_field :meal_id, :value => meal.id %>
  
              <%= f.collection_select :day_id, Day.all, :id, :title, {}, class: 'form-control' %>

              <span class='input-group-btn'>
                <%= f.submit 'add', class: 'btn btn-default' %>
              </span>
            </div>
          <% end %>
        </td>
    </tr>
  <% end %>
</table>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render partial: 'form' %>

app/views/meals/show.html.erb
<h1>Meal</h1>

<ul>
  <% @meal.recipes.each do |recipe| %>
    <li>
      <%= recipe.title %>
    </li>
  <% end %>
</ul>

app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => { :multipart => true } do |f| %>
  <% if @recipe.errors.any? %>
    <h2>Error:</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class='row'>
    <div class='form-group'>
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
  
    <div class='form-group'>
      <%= f.label :calories, class: 'col-sm-2 control-label' %>
      <div class='col-sm-1'>
        <%= f.text_field :calories, class: 'form-control' %>
      </div>
    </div>
  
    <div class='form-group'>
      <%= f.label :carbs, class: 'col-sm-2 control-label' %>
      <div class='col-sm-1'>
        <%= f.text_field :carbs, class: 'form-control' %>
      </div>
    </div>
  
    <div class='form-group'>
      <%= f.label :fats, class: 'col-sm-2 control-label' %>
      <div class='col-sm-1'>
        <%= f.text_field :fats, class: 'form-control' %>
      </div>
    </div>
  
    <div class='form-group'>
      <%= f.label :protein, class: 'col-sm-2 control-label' %>
      <div class='col-sm-1'>
        <%= f.text_field :protein, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :servings, class: 'col-sm-2 control-label' %>
      <div class='col-sm-1'>
        <%= f.text_field :servings, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :url, class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :notes, class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.text_area :notes, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :photo, class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.file_field :photo, class: 'form-control' %>
      </div>
    </div>

  </div>

  <h2>Ingredients</h2>

  <% if not @recipe %>
    <%= f.label :batch_ingredients, class: 'col-sm-2 control-label' %>
    <%= f.text_area :batch_ingredients, class: 'form-control' %>
  <% end %>

  <div class='row'>
    <%= f.fields_for :ingredients do |ingredients_form| %>
      <div class='col-sm-2'>
        <%= ingredients_form.text_field :description, class: 'form-control' %>
      </div>
    <% end %>
  </div>

  <div class='row'>
    <div class='form-group'>
      <%= f.submit class: 'submit' %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render partial: 'form' %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= link_to "New recipe", new_recipe_path %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th></th>
      <th>Calories</th>
      <th>Carbohydrates (g)</th>
      <th>Fats (g)</th>
      <th>Protein (g)</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to recipe.title, recipe_path(recipe.id) %></td>
      <td><%= recipe.colorized_calories %></td>
      <td><%= recipe.colorized_carbs %></td>
      <td><%= recipe.colorized_fats %></td>
      <td><%= recipe.colorized_protein %></td>
      <td><%= link_to '(edit)', edit_recipe_path(recipe.id) %></td>
      <td>
        <% if recipe.photo.exists? %>
          <%= image_tag recipe.photo.url(:thumb) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render partial: 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<% if @recipe.photo.exists? %>
  <%= image_tag @recipe.photo.url(:medium) %>
<% end %>

<table>
  <% %w(calories carbs fats protein).each do |n| %>
    <% if @recipe[n] %>
      <tr>
        <td><%= @recipe.send('colorized_' + n) %></td>
        <td><%= n %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<% if not @recipe.url.nil? %>
  <p>
    Source: <%= link_to @recipe.url, @recipe.url %>
  </p>
<% end %>

<% if @recipe.servings %>
  <p>
    <%= @recipe.servings %> Serving<%= 's' if @recipe.servings > 1 %>
  </p>
<% end %>

<% if @recipe.ingredients.length > 0 %>
  <h2><%= @recipe.ingredients.length %> Ingredients</h2>
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
      <li>
        <%= ingredient.description %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @recipe.directions %>
  <h2>Directions</h2>

  <p>
    <%= @recipe.directions.gsub("\n", "</p><p>").html_safe %>
  </p>
<% end %>


<%= link_to "Back", recipes_path %>

app/views/shopping/list.html.erb
<h1>Shopping List</h1>

<% @days.each do |day| %>
  <% next if not @recipe_ids.keys.include?(day.id) %>

  <h2><%= day.title %></h2>
  
  <% day.meals.each do |meal| %>

    <% next if not @recipe_ids[day.id].keys.include?(meal.id) %>

    <% meal.recipes.each do |recipe| %>

      <% next if not @recipe_ids[day.id][meal.id].include?(recipe.id) %>

      <strong><%= recipe.title %></strong>
      <ul>
        <% recipe.ingredients.each do |ingredient| %>
          <li><%= ingredient.description %></li>
        <% end %>
      </ul>

      <% if @directions and not recipe.directions.nil? %>
        <p>
          <%= recipe.directions.gsub("\n", "</p><p>").html_safe %>
        </p>
      <% end %>

      <hr />
    <% end %>
  <% end %>
<% end %>

app/views/shopping/setup.html.erb
<h1>Shopping List</h1>

<%= form_for :shopping, url: shopping_list_url do |f| %>

  <%= f.label :directions, 'Include directions' %>
  <%= f.check_box :directions %>

  <% @days.each do |day| %>
    <div class='day'>
      <% next if day.meals.length == 0 %>

      <h2><%= check_box_tag "shopping[day_ids][]", day.id, true, class: 'day' %> <%= day.title %></h2>

      <ul>
        <% day.meals.each do |meal| %>
          <li>
            <div class='meal'>
              <%= check_box_tag "shopping[meal_ids][]", meal.id, true, class: 'meal' %>

              <strong><%= meal.meal_type %></strong>

              <ul>
                <% meal.recipes.each do |recipe| %>
                  <li>
                    <%= check_box_tag "shopping[recipe_ids][day_#{day.id}][meal_#{meal.id}][]", recipe.id, true, class: 'recipe' %>
                    <%= recipe.title %>
                  </li>
                <% end %>
              </ul>
            </div>
          </li>
        <% end %>
      </ul>

    </div>

  <% end %>

  <%= f.submit 'Make list' %>
<% end %>